=== ravihuang/desktopassistant/activeWindow/testlink.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" elementFormDefault="qualified">
  <xs:element name="testsuite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="node_order" />
        <xs:element ref="details" />
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="testcase"/>
          <xs:element ref="testsuite"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="node_order" type="xs:unsignedInt" default="1"/>
  <xs:element name="details" type="xs:string"/>
  <xs:element name="testcase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="node_order"/>
        <xs:element ref="externalid"/>
        <xs:element ref="version"/>
        <xs:element ref="summary"/>
        <xs:element ref="preconditions"/>
        <xs:element ref="execution_type"/>
        <xs:element ref="importance"/>
        <xs:element ref="steps"/>
        <xs:element ref="custom_fields"/>
        <xs:element ref="requirements" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="internalid" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="externalid" type="xs:unsignedInt"/>
  <xs:element name="version" type="xs:unsignedInt"/>
  <xs:element name="summary" type="xs:string" />
  <xs:element name="preconditions" type="xs:string"/>
  <xs:element name="execution_type" type="xs:unsignedInt"/>
  <xs:element name="importance" type="xs:unsignedInt"/>

  <xs:element name="steps">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="step" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="step">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="step_number"/>
        <xs:element ref="actions"/>
        <xs:element ref="expectedresults"/>
        <xs:element ref="execution_type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="step_number" type="xs:unsignedInt"/>
  <xs:element name="actions" type="xs:string" />
  <xs:element name="expectedresults" type="xs:string" />
  <xs:element name="custom_fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="custom_field" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="custom_field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string" />
  <xs:element name="value" type="xs:string" />
  <xs:element name="requirements" >
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="requirement" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="requirement">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="req_spec_title"/>
        <xs:element ref="doc_id"/>
        <xs:element ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="req_spec_title" type="xs:string" />
  <xs:element name="doc_id" type="xs:string" />
  <xs:element name="title" type="xs:string" />
</xs:schema>

=== ravihuang/desktopassistant/activeWindow/all_testsuites_u8.xml
<?xml version="1.0" encoding="UTF-8"?>	
<testsuite xsi:noNamespaceSchemaLocation="file:///f:/vs/testlink.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="NFE">
	
<node_order><![CDATA[1]]></node_order>
<details><![CDATA[]]> 
</details><testsuite name="baseline">
<node_order><![CDATA[1]]></node_order>
<details><![CDATA[<p>基线测试套</p>]]> 
</details>
<testcase internalid="3" name="SVT_NFE_WIFIR2_FUNC_0010">
	<node_order><![CDATA[0]]></node_order>
	<externalid><![CDATA[1]]></externalid>
	<version><![CDATA[1]]></version>
	<summary><![CDATA[<p>摘要</p>]]></summary>
	<preconditions><![CDATA[<p>&nbsp;preset&nbsp;</p>]]></preconditions>
	<execution_type><![CDATA[2]]></execution_type>
	<importance><![CDATA[2]]></importance>
<steps>
<step>
	<step_number><![CDATA[1]]></step_number>
	<actions><![CDATA[<p>&nbsp;step1:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect1:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>

<step>
	<step_number><![CDATA[2]]></step_number>
	<actions><![CDATA[<p>&nbsp;step2:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect2:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>
</steps>
<custom_fields>
	<custom_field>
		<name><![CDATA[test_type]]></name>
		<value><![CDATA[]]></value>
	</custom_field>	<custom_field>
		<name><![CDATA[test_sample]]></name>
		<value><![CDATA[]]></value>
	</custom_field>
</custom_fields>
<requirements>
		<requirement>
			<req_spec_title><![CDATA[hrhd]]></req_spec_title>
			<doc_id><![CDATA[DS_PLUGIN_1]]></doc_id>
			<title><![CDATA[asdasd]]></title>
		</requirement>
	</requirements>
</testcase>

<testcase internalid="7" name="SVT_NFE_WIFIR2_FUNC_0020">
	<node_order><![CDATA[1]]></node_order>
	<externalid><![CDATA[2]]></externalid>
	<version><![CDATA[1]]></version>
	<summary><![CDATA[<p>&nbsp;概要&nbsp;</p>]]></summary>
	<preconditions><![CDATA[<p>&nbsp;前提</p>]]></preconditions>
	<execution_type><![CDATA[1]]></execution_type>
	<importance><![CDATA[2]]></importance>
<steps>
<step>
	<step_number><![CDATA[1]]></step_number>
	<actions><![CDATA[<p>&nbsp;step1:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect1:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>

<step>
	<step_number><![CDATA[2]]></step_number>
	<actions><![CDATA[<p>&nbsp;step2:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect2:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>
</steps>
    <custom_fields>
	    <custom_field>
		    <name><![CDATA[test_type]]></name>
  		    <value><![CDATA[a;b; c d]]></value>
	    </custom_field>
        <custom_field>
		    <name><![CDATA[test_sample]]></name>
		    <value><![CDATA[啊的飒爽的]]></value>
 	    </custom_field>
    </custom_fields>
    <requirements>
		<requirement>
			<req_spec_title><![CDATA[hrhd]]></req_spec_title>
			<doc_id><![CDATA[DS_PLUGIN_1]]></doc_id>
			<title><![CDATA[asdasd]]></title>
		</requirement>
	</requirements>
</testcase>
<testsuite name="棒棒糖">
<node_order><![CDATA[2]]></node_order>
<details><![CDATA[]]> 
</details><testsuite name="ttc">
<node_order><![CDATA[1]]></node_order>
<details><![CDATA[]]> 
</details><testsuite name="ttd">
<node_order><![CDATA[1]]></node_order>
<details><![CDATA[]]> 
</details>
<testcase internalid="14" name="asd">
	<node_order><![CDATA[100]]></node_order>
	<externalid><![CDATA[3]]></externalid>
	<version><![CDATA[1]]></version>
	<summary><![CDATA[]]></summary>
	<preconditions><![CDATA[]]></preconditions>
	<execution_type><![CDATA[1]]></execution_type>
	<importance><![CDATA[2]]></importance>
<steps>
<step>
	<step_number><![CDATA[1]]></step_number>
	<actions><![CDATA[<p>&nbsp;step1:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect1:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>

<step>
	<step_number><![CDATA[2]]></step_number>
	<actions><![CDATA[<p>&nbsp;step2:</p>]]></actions>
	<expectedresults><![CDATA[<p>&nbsp;expect2:</p>]]></expectedresults>
	<execution_type><![CDATA[2]]></execution_type>
</step>
</steps>
<custom_fields>
	<custom_field>
		<name><![CDATA[test_type]]></name>
		<value><![CDATA[]]></value>
	</custom_field>	<custom_field>
		<name><![CDATA[test_sample]]></name>
		<value><![CDATA[]]></value>
	</custom_field>
</custom_fields>
    <requirements>
		<requirement>
			<req_spec_title><![CDATA[hrhd]]></req_spec_title>
			<doc_id><![CDATA[DS_PLUGIN_2]]></doc_id>
			<title><![CDATA[asdasd]]></title>
		</requirement>
	</requirements>
</testcase>
</testsuite></testsuite></testsuite></testsuite></testsuite>
